CLASS_NAMES = [
    "apple",
    "banana",
    "orange",
    "lemon",
    "mango",
    "grapes",
    "pineapple",
    "watermelon",
    "pear",
    "paprika",
    "tomato",
    "chilli pepper",
    "bell pepper",
    "cucumber",
    "lettuce",
    "spinach",
    "potato",
    "sweetpotato",
    "carrot",
    "beetroot",
    "radish",
    "onion",
    "garlic",
    "ginger",
    "corn",
    "sweetcorn",
    "peas",
    "soy beans",
    "capsicum",
    "eggplant",
    "cauliflower",
    "turnip",
    "pomegranate",
    "kiwi",
    "jalepeno"
]